import { Platform } from "react-native";
import { API_BASE_URL } from "@/constants/api";
import manifest from "./documentManifest.json";

// Generated by backend/scripts/build_offline_pdfs.py
export interface KnowledgeDoc {
  filename: string; // original relative path (matches backend RAG "source")
  name: string;
  size_kb: number;
  url: string; // local web path under /pdfs/...
}

export const DOCUMENTS: KnowledgeDoc[] = manifest as KnowledgeDoc[];

/**
 * Resolve the openable URL for a document.
 * - Web: bundled static asset under /pdfs (no backend request).
 * - Native: falls back to the backend /documents endpoint.
 */
// This project's tsconfig does not include the DOM lib, so reach `window`
// through a typed view of globalThis (same pattern as lib/alert.ts).
const webGlobal = globalThis as unknown as {
  location?: { origin?: string };
};

export function getDocUrl(doc: { filename: string; url?: string }): string {
  if (Platform.OS === "web") {
    const path =
      doc.url ?? `/pdfs/${doc.filename.split("/").map(encodeURIComponent).join("/")}`;
    const origin = webGlobal.location?.origin;
    return origin ? origin + path : path;
  }
  return `${API_BASE_URL}/documents/${encodeURIComponent(doc.filename)}`;
}
